### ISSUE TITLE
performance decrease when widget is saved

### ISSUE THREAD

**Issue by gitdemont** [dmurdoch/rgl#106]
Hi,

Strangely, when a widget is saved to a standalone general webpage the interactivity with the scene is strongly decrease in comparison to what can be displayed within Rstudio viewer panel 

A min reprex:

library(rgl)
n = 1000
open3d(useNULL = TRUE)
plot3d(x = rnorm(n),y = rnorm(n),z = rnorm(n), type = "s")
widget <- rglwidget()
widget # to display the widget
fname <- tempfile(fileext = paste0(n, "_.html"))
htmlwidgets::saveWidget(widget = widget, file = fname, selfcontained = TRUE)
shell(fname) # this should allow to open the created html with default browser

**Comment by dmurdoch** [comment]
There are a few possible explanations here.

First, rgl tends to fight with RStudio for control of the mouse, so it sometimes  completely misses mouse events.  It may be that's why it looks faster:  it's just ignoring things that don't matter.

Another possibility is that the event handling is just better in RStudio.  I'd try the web page in a different browser to see.  (RStudio uses a version of Chromium, like Google Chrome.)  For example, in the X11 window (not using WebGL) you can turn off mouse events when the button is not down.  I don't try to do this in WebGL, but maybe the browser in RStudio does it automatically.

I don't really know how to test for a difference between rgl doing things badly and the browser doing things more efficiently.  If you can think of a test or spot some errors in the rgl code, let me know, otherwise I can't think of a way to address this.

**Comment by gitdemont** [comment]
Obviously, I have no idea where it comes from. So I can not spot a portion of code that could lead to this behaviour.

I tested with firefox, chrome and edge. And the issue appears in each one.

Thanks to the new update of rgl package with setUserCallbacks (this update is really cool !),
I was able to include a callback showing fps (I am far from being a specialist, but it seems to work).
I hope, this will help to identify a solution.
See [rgl_fps.zip](https://github.com/dmurdoch/rgl/files/6487928/rgl_fps.zip)

Within Rstudio I am around 60.
With the standalone page in chrome, I am struggling to reach 4.

**Comment by dmurdoch** [comment]
One possibility is different graphics support, hardware vs software.  Here's how to find the details:

 RStudio:  Go to Help | Diagnostics | Show GPU Diagnostics

 Chrome:  Go to chrome://gpu/

 Firefox:  Go to about:support, and scroll down to Graphics.  (There's a lot more detail there...)

**Comment by gitdemont** [comment]
Your last reply was really helpful !
There is a big difference between Rstudio command line options and the one that were used by default in my google chrome.
After some tries I found that tweaking some options did significantly improve things !

For readers: 
In Chrome:
chrome://flags/#enable-gpu-rasterization, choose Enable, then Relaunch
chrome://flags/#use-angle, choose OpenGL, then Relaunch

Or run with command line --enable-gpu-rasterization --use-angle=gl

Thanks for pointing this out
