### ISSUE TITLE
.onLoad failed in loadNamespace() for 'rgl' error when the package is installed on a mapped drive

### ISSUE THREAD

**Issue by Antsushi** [dmurdoch/rgl#148]
Some background before explaining the issue: my work place has set up the Z drive as an individual "cloud" storage drive for each user. For example, if my username is mkl and I log into one of the machines at work, I will be able to access my files through this address:

\\files.companyname.ac.uk/usersm/mkl/Home/My Files/

The address above can also be read as Z:/.

Inside this drive, we have our R installation, including all the libraries. The default library path is as follows:

\\files.companyname.ac.uk/usersm/mkl/Home/My Files/R/R-4.1.1/library/ 

Or alternatively:

Z:/My Files/R/R-4.1.1/library/ 

The issue is that after a successfull installation of 'rgl', we get this error (it's been encountered on every machine so far):

```
Error: package or namespace load failed for ‘rgl’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: getDLLRegisteredRoutines.character(dynlib, addNames = FALSE)
  error: No DLL currently loaded with name or path ‘\\files.companyname.ac.uk/usersm/mkl/Home/My Files/R/R-4.1.1/library/rgl/libs/x64/rgl.dll’
```
Running the following code loads the package:

`library(rgl, lib.loc = "Z:/My Files/R/R-4.1.1/library")`

However, the issue comes when running the function slider3d() from the package 'Morpho'. 'Morpho' requires 'rgl' to be installed, but because I cannot initiate both libraries at the same time, I need to load 'rgl' first and only then I can load 'Morpho'. Running the function slider3d() produces the following error:

```
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  worker initialization failed: package or namespace load failed for 'Morpho':
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: getDLLRegisteredRoutines.character(dynlib, addNames = FALSE)
  error: No DLL currently loaded with name or path '\\files.companyname.ac.uk/usersm/mkl/Home/My Files/R/R-4.1.1/library/rgl/libs/x64/rgl.dll'
```
It seems that something within that function expects 'Morpho' and 'rgl' to load at the same, or be in the same directory. 

The issue here isn't really with slider3d(), but with 'rgl' failing to load. It seems there is a problem with the path to the .dll file, however every other package has the exact same file and folder structure as 'rgl', and we are not experiencing any issues loading them into R. Why would this be happening specifically with this package?

**Comment by dmurdoch** [comment]
`rgl` has a very unusual structure, and that's what's causing the problem on your systems, which have an unusual file layout.  The `rgl` issue is that it has two copies of the DLL, one which uses OpenGL, and one which doesn't.  It tries to load them manually in the .onLoad function, and that's not working for you.

I'm afraid I'm not going to be able to debug this for you, but if you can work out what is necessary so that it produces a valid directory name on your systems, I'd be happy to consider a PR.

**Comment by dmurdoch** [comment]
Actually, on Windows there's only one version of the DLL (since OpenGL can always be assumed to be available), but the loading is done using the same mechanism, not the regular R automatic mechanism.  

I've spotted one change that might help.  Can you install `rgl` from source, using

    remotes::install_github("dmurdoch/rgl@issue148")

This uses a slightly different mechanism during startup, which might be more reliable.

**Comment by Antsushi** [comment]
Thank you dmurdoch. I was wondering about the second .dll as I couldn't find it! However, your solution works. I can now load the package from the Z:/ drive. Thanks!

**Comment by dmurdoch** [comment]
Great!  I'll merge that PR.

**Comment by Antsushi** [comment]
Hi dmurdoc,

So everything seems to be working fine apart from the function legend3d(). Whenever I run it R crashes and I get a message that says that "R has ecnountered a fatal error". It only started happening when I installed rgl using the method you suggested. Is there a way for me to debug this so I could provide you with something to troubleshoot the issue?

**Comment by dmurdoch** [comment]
Low level debugging on WIndows is a little hard.  You need to debug R in the gdb debugger, but the method for doing that on Unix-alikes doesn't work on Windows.  The basic idea on Windows is to start R first, then run gdb in a different window and attach it to the R process.  You can find the process number (PID) in Task Manager.  I forget exactly what the steps are in gdb, but it's something like starting it, then executing "attach <PID>", then c for continue.  

gdb can do source level debugging of rgl, but it will probably have trouble finding the source files; I also forget the details in how you tell it where they are.

Once you have gdb attached and R is running again, trigger the error.  A segfault will be caught by gdb and it will give some info about the location.

You could also work on putting together a minimal R script to trigger the error; if I can trigger it, I can probably find the cause faster than you can.

**Comment by Antsushi** [comment]
Maybe a code example then would be better. I reinstalled `rgl` on my latop which has a normal file structure (no cloud/server files/folders, everything is local) and no issues loading the package using 

`remotes::install_github("dmurdoch/rgl@issue148")`

And I am getting same issue with `legend3d()`

Running this code will crash R when it reaches the function:

```
set.seed(1)
mat <- matrix(rnorm(12), ncol = 3)
plot3d(mat)
legend3d("topleft", "testing")
```

After reinstalling `rgl` using 

`install.packages("rgl")`

The issue is resolved.

**Comment by dmurdoch** [comment]
Thanks.  I can reproduce the issue on Windows, but not on MacOS. I guess I need to relearn Windows debugging.

**Comment by dmurdoch** [comment]
I strongly suspect this issue is related to this change:  https://github.com/dmurdoch/rgl/commit/da5aa76141f1d722bee1a1df77418954a4e9f832, which had news entry "Textures can now take a vector of filenames which will be used as a "mipmap".  This may be used in`legend3d()` to give legends that adjust to the size 
of the display.  If I can't spot what's going wrong on Windows, I may undo that change; it was not as useful as I hoped it would be.

**Comment by dmurdoch** [comment]
The issue148 branch now has the multi-file textures undone.  Could you give it a try and see if it's working now?

**Comment by Antsushi** [comment]
Everything seems to be working well now, thanks!
