### ISSUE TITLE
Some axis labels are not shown in a PDF generated with rmarkdown and knitr

### ISSUE THREAD

**Issue by ferenci-tamas** [dmurdoch/rgl#197]
Consider the following code:

```
rgl::view3d(userMatrix = matrix(c(0.74, -0.18, 0.44, 0, 0.67, 0.23, -0.70, 0, -0.02, 0.95,
                                  0.30, 0, 0, 0, 0, 1), nc = 4))
rgl::plot3d(rnorm(20), rnorm(20), rnorm(20))
```

This generates the following figure:

![kép](https://user-images.githubusercontent.com/25476790/159811519-fdd2ebab-1cfe-4b9b-be55-5182a882d539.png)

However, when using the _exact same_ code within an rmarkdown file that is rendered to PDF using `knitr`, i.e., 

````
---
title: "Untitled"
output:
  pdf_document: default
---

```{r, setup}
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, dpi = 300, dev = "ragg_png")
Sys.setenv(CHROMOTE_CHROME = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe")
options(rgl.useNULL = TRUE)
rgl::setupKnitr(autoprint = TRUE)
```

Plot:

```{r}
rgl::view3d(userMatrix = matrix(c(0.74, -0.18, 0.44, 0, 0.67, 0.23, -0.70, 0, -0.02, 0.95,
                                  0.30, 0, 0, 0, 0, 1), nc = 4))
rgl::plot3d(rnorm(20), rnorm(20), rnorm(20))
```
````

 this is what I get:

![kép](https://user-images.githubusercontent.com/25476790/159811897-50efd87b-1b08-4c8a-9ced-59380117d090.png)

For some reason, tick labels from two of the three axes disappeared...

* **rgl Version**: 0.108.26
* **R Version**: 4.2.1
* **Platform**:  Windows 10

**Comment by dmurdoch** [comment]
The difference between the two situations is that the first one uses the built-in display driver in rgl and displays locally in R, while the second uses the WebGL driver and displays in a browser (looks like Edge in your case, but I see the same in Chrome).  In either case there's also a step taking a screenshot of the display.

I'm not exactly sure why the tick labels aren't being shown in WebGL.  I thought at first they were just being clipped, but the axis labels aren't clipped, and they're further out, so that's not it.  That looks like a bug.

As a workaround, you can insert a screenshot of the internal display instead of the WebGL display by making the following changes:

1.  Make sure the `webshot2` package is not available.  
2. Set `options(rgl.useNULL = FALSE)`.

If you do this, there will be other visible differences in the display as well.  Usually the WebGL display looks better (it's using a more modern version of OpenGL).  I've been thinking I should make it easier to force the internal display (sometimes `webshot2` is extremely slow); this provides more evidence that would be a good idea.
