### ISSUE TITLE
Documentation for setting the camera angle programmatically is hard to find

### ISSUE THREAD

**Issue by hughjonesd** [dmurdoch/rgl#203]
This is an enhancement request. I was trying to set the camera angle within a knitr document. I worked it out using stackoverflow, but it was hard to find documentation in either the vignettes or reference.

In particular, I looked in "controlling the look of the scene", and elsewhere in introductory vignette. I tried `?rotate3d` but it didn't seem informative. I looked at `?view3d` and `?observer3d`. I think `view3d` might work but I don't know how `theta` and `phi` apply in a 3d setting. Eventually I used `rotate3d` to rotate `r3dDefaults$userMatrix` in a call to `open3d()`.

I think this might be useful as an addition to the intro vignette. Alternatively, some general documentation on polar coordinates in appropriate places might help.

Thanks for a great package.

* **rgl Version**: 0.108.3

**Comment by dmurdoch** [comment]
Sounds like a good idea.  Could you put together a PR for it?

**Comment by hughjonesd** [comment]
OK, I can try. 

* Is `open3d(userMatrix = rgl::rotate3d(rgl::r3dDefaults$userMatrix, ...)` indeed the canonical thing to do? 
* My guess is that `theta` is horizontal rotation (i.e. around the z axis) and `phi` is vertical rotation (i.e. going from flat to top to flat to bottom), is that right?

**Comment by dmurdoch** [comment]
I'm not sure I understand what you mean by "the canonical thing to do".  `open3d()` with no arguments will set `par3d("userMatrix")` to `rgl::r3dDefaults$userMatrix`, so that's what happens by default, it's not something you need to specify.

The OpenGL labels for the axes are `x` going horizontally in the display, `y` going vertically in the display, and `z` being depth into the display.  So I think your verbal description is correct, but saying `theta` rotates about `z` is wrong:

 In `view3d(theta, phi)`, `theta` is a rotation in degrees around the `y` axis, and `phi` is a rotation in degrees around the `x` axis.  If both are specified, the `theta` rotation is applied first.

**Comment by hughjonesd** [comment]
I meant, what's the easiest way to set the viewpoint when you start a plot. I think the best answer is "just use `view3d`".

OK. One issue for beginners is that if you do e.g. `plot3d(1:10, 1:10, 1:10)` the z axis is initally pointing upwards rather than being "depth". 

See #204 for a first shot.

**Comment by dmurdoch** [comment]
I added some tweaks and merged #204
