### ISSUE TITLE
library(rgl) segfaults in RStudio

### ISSUE THREAD

**Issue by ms609** [dmurdoch/rgl#208]
Related: #105?

* **rgl Version**: 0.108.31 (and CRAN release)
* **R Version**: 4.2.0 RC (2022-04-21 r82226 ucrt)
* **RStudio version**: 2022.06.0 Build 322
* **Platform**: Windows 10 x64

`library(rgl)` works in the R4.2 GUI, but in RStudio I see "R Session Aborted".  In R 4.1.3 and the same RStudio version rgl loads fine.

Possibly unrelated, but I've seen the same pattern of crashing in 4.2/not crashing in R4.1 in my packages when `throw` is called: this worked fine in 4.1.3 but crashes 4.2.0.  So I wonder whether this could be related to an error handling mechanism that's not officially supported by R?

**Comment by dmurdoch** [comment]
That sounds like an RStudio problem, doesn't it?  There are a lot of changes in R 4.2.0 on Windows, and maybe RStudio isn't completely compatible with them.

**Comment by ms609** [comment]
Reported to RStudio – thanks for taking a look.

**Comment by kevinushey** [comment]
I'm seeing the following with the Visual Studio debugger (after using cv2pdb to convert debug symbols from DWARF to PDF)

<img width="1120" alt="Screen Shot 2022-04-22 at 12 40 14 PM" src="https://user-images.githubusercontent.com/1976582/164782999-d913e850-8401-4bf9-be96-6df4ed999b6f.png">

I think the problem here is that `open("nul", O_WRONLY)` is failing in RStudio, but its failure is not checked. The later call to `dup2()` is hence invalid (as `devNull` is not a valid handle).

One way to fix this in `rgl` would be to check whether `devNull` is valid, and only attempt to redirect stderr to `devNull` if that handle is valid.

**Comment by kevinushey** [comment]
You might be able to use `freopen("NUL", "a", stderr);` to redirect `stderr` to `NUL:` -- apparently this works within RStudio, while directly opening `NUL` via `open()` or `fopen()` does not.

**Comment by dmurdoch** [comment]
@kevinushey:  thanks for tracking this down.  I'll try some fixes this weekend.

**Comment by dmurdoch** [comment]
@ms609:  The bad code was put in a couple of years ago to suppress a spurious error message that appeared on `stderr` on some systems when OpenGL was initialized.  I don't know if it ever appeared on Windows.   A simple workaround that should avoid the bad code is to set 

    options(rgl.debug = TRUE)

before loading `rgl`, so the error message will not be suppressed if it happens on your system.
