### ISSUE TITLE
readOBJ() fails while triangulating square polygon face

### ISSUE THREAD

**Issue by trevorld** [dmurdoch/rgl#258]
* `rgl::readOBJ()` throws an error triangulating a square face (of a cube)
* `readobj::read.obj()` reads it fine

Reproducible example:

```r
obj_text <- "
## geometric vertices
# cube 1
v 0 1 1
v 0 0 1
v 1 0 1
v 1 1 1
v 0 1 0
v 0 0 0
v 1 0 0
v 1 1 0

# cube 2
v 2 1 1
v 2 0 1
v 3 0 1
v 3 1 1
v 2 1 0
v 2 0 0
v 3 0 0
v 3 1 0

## polygonal face elements
g cube_1
f 1 2 3 4
f 8 4 3 7
f 1 4 8 5
f 6 5 8 7
f 1 5 6 2
f 3 2 6 7

g cube_2
f  9 10 11 12
f 16 12 11 15
f  9 12 16 13
f 14 13 16 15
f  9 13 14 10
f 11 10 14 15
"
writeLines(obj_text, "cubes.obj")
```
```r
library("rgl")
rgl::readOBJ("cubes.obj")
```
```r
Error in if (!diff(range(x))) x <- xyz$z else if (!diff(range(y))) y <- xyz$z : 
  missing value where TRUE/FALSE needed
```

In contrast ``readobj::read.obj()` seems to handle it fine:

```r
library("readobj")
library("rgl")
mesh <- readobj::read.obj("cubes.obj", convert.rgl=TRUE)
rgl::shade3d(mesh)
rgl::rgl.snapshot("cubes.png")
```

![cubes](https://user-images.githubusercontent.com/2433259/182678846-6b61d242-aaf2-41f7-8939-e5577384dd09.png)

* **rgl Version**: 0.109.12
* **R Version**: 4.2.1
* **Platform**: Linux fsi-pesd 5.4.0-121-generic 137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dmurdoch** [comment]
The problem is that `rgl::readOBJ` assumes items in the faces lines are separated by single spaces, and some of your lines (e.g. `f  9 10 11 12`) have two space separators.  It certainly makes more sense to accept the double space than to fail.  I'll fix this soon in the devel version, but probably won't submit a new revision to CRAN until next month.
