### ISSUE TITLE
Bug visualization rglwidget()

### ISSUE THREAD

**Issue by SbastianGarzon** [dmurdoch/rgl#314]
* **rgl Version**: latest development version 
* **R Version**: 4.2.2 
* **Platform**: Ubuntu 22.04  

I'm having problems visualizing surfaces with the rglwidget() while using Rayshader (Quarto document)

Here is a reproducible error:

```
library(tidyverse)
library(rayshader)
library(rgl)

set.seed(2)
elevation_matrix <- matrix(rnorm(25) , nrow = 10,ncol = 10)

elevation_matrix %>% 
  height_shade(texture = topo.colors(256)) %>%
  plot_3d(elevation_matrix,baseshape = "rectangle")

rglwidget()

```
# rgl output:

![rgl](https://user-images.githubusercontent.com/8647343/217851090-fa7893b3-2261-463c-9425-6fe053049b24.png)

# rglwidget output (HTML):

![rglwidget](https://user-images.githubusercontent.com/8647343/217851347-416c2972-f4ed-4403-95bd-77c5e637192e.png)

# Same error in another (more complex) Rayshader viz.

![rgl_city](https://user-images.githubusercontent.com/8647343/217852116-89db00ed-70d9-406c-8c43-a3bab6feae0d.png)

**Comment by dmurdoch** [comment]
I see the issue in your first example.   Hopefully easy to fix.

**Comment by dmurdoch** [comment]
This is definitely a bug in `rgl`.  It's triggered by the fact that the back of the surface is culled, but I don't see a way to avoid that (other than editing the source to `rayshader::plot_3d`).  I'll track down the cause and patch it soon.

**Comment by dmurdoch** [comment]
I found it.  The problem was that `scene3d()` (used by `rglwidget()`) removed the normals for the objects when it saw the object was unlit.  That meant that they needed to be recalculated to determine front and back in order to cull the back, but the recalculation was incorrect because of the indexing used by `rayshader::plot_3d()`.

I'll stop the removal, and not allow two-sided indexed rendering without normals.  Look for rgl 1.0.10 sometime later today.
