### ISSUE TITLE
Could we fix parsing on pre-release macOS versions to avoid a bogus error in checks?

### ISSUE THREAD

**Issue by barracuda156** [dmurdoch/rgl#419]
@dmurdoch Could we support parsing devel versions of macOS? I get this when running tests:
```
Error : invalid version specification ‘10.0.0d2’
```
This does not prevent tests from running further, but it would be nice to get rid of this. The version _is_ valid in fact, and Apple kern headers specify pre-release versions. It is not an error.
```
* using R version 4.3.3 (2024-02-29)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0
    GNU Fortran (MacPorts gcc12 12.3.0_3+stdlib_flag) 12.3.0
* running under: OS X Snow Leopard 10.6
```

P. S. This is the first time I see it with an `R` package in fact. So this should be avoidable, I believe.

**Comment by dmurdoch** [comment]
That message isn't coming from `rgl` code.  There's a message like that in base R in `.make_numeric_version()`, which is called by `numeric_version()`, `package_version()`, and `R_system_version()`.  `rgl` calls `getRversion()` during configuration, so that might be the trigger; it calls `package_version()`.  However, I don't think that's something I can avoid.

If you can narrow down the location of the source of the message, it's possible I could fix it.

**Comment by barracuda156** [comment]
@dmurdoch Sorry, this was forgotten. I will need to look into that again. (This issue pops up every once in a while with different unrelated apps, it is probably wrong `sed` expression somewhere in R scripts.)
