### ISSUE TITLE
Font support needs updating

### ISSUE THREAD

**Issue by dmurdoch** [dmurdoch/rgl#8]
The official release of FTGL hasn't been updated in a long time, but there are various bug fixes available on Github.  Do any of those matter to rgl?  

It would be nice to be able to allow rotated text.  This would require texture-based fonts instead of the current bitmap based fonts.

**Comment by psychemedia** [comment]
Noting that with the current build installed from Github on a Mac, I'm getting "FreeType not supported in this build" as well as "this build does not include OpenGL functions". Trying to roll back to the version on CRAN, when running with `rayshader`, textures seem not to render on widget models. I'm not sure what version I'd been working with previously but those errors were new to me and hadn't appeared when running code previously.

**Comment by dmurdoch** [comment]
There were a couple of quick updates to CRAN just a day or two ago; you were likely using a release before those, maybe 0.104.16.  I expect you'll have similar trouble building it:  it might be easier to restore the rgl directory `system.file(package="rgl")` from a Time Machine backup if you've got one.

**Comment by psychemedia** [comment]
One version,  no backups...! ;-)

I do generally work in containers but because I kept dropping into RGL widget it was more convenient just to work from desktop... As I've been evaluating many many packages, I've also been quite cavalier in installing and updating things, figuring I'm starting from a pretty much clean slate anyway. I've also been out of R for a couple of years and haven't got back in to whatever tools are around to snapshot package version manifests.

Ne'er mind, it's an exploratory hobby side project  thing and there are plenty of other directions meandering directions associated with it. I'll maybe return to the 3D bit after I chase some of the other bits down (they'll all hook up eventually I hope!)

Is there a timeline / plan for where rgl is going? Are the OpenGL/Freetype things likely to make a return over coming weeks/months, or are they now written out? I'm very much a casual user but would be good to get a feel for what will be/may be/won't be possible in upcoming versions.

(Loving the package by the way. So many possibilities with what to do with it. I just noticed the `crosstalk` features too, which I need to take a walk to ponder the possibilities of!)

**Comment by dmurdoch** [comment]
@psychemedia , I'm hiding our comments on this thread so as not to hijack it.  Your install problems should be addressed better by the README:  rgl isn't an easy install.  As to long term plans and timelines:  there are no timelines.  The wish list is the list of topics I entered as issues, but it tends to be very fluid.  I expect in the short term I'll spend some time to get a pkgdown website working.  (It's trivial to get the website online, the hard part is getting the rgl examples to show.)

**Comment by dmurdoch** [comment]
This is now a dup of #312
